dnsimple/terraform-provider-dnsimple

- README.md
- dnsimple/provider.go
- dnsimple/provider_test.go
- website/docs/index.html.markdown
API v1 is gone. The deprecation has been in place for over 3 years. I'm taking the opportunity of the switch to the plugin SDK to cleanup the code.
> Remove deprecated email config

- dnsimple/config.go
- go.mod
- go.sum
- vendor/github.com/dnsimple/dnsimple-go/LICENSE.txt
- vendor/github.com/dnsimple/dnsimple-go/dnsimple/dnsimple.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/httpclient/useragent.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
- vendor/modules.txt
This PR is standardizing the user agent as recommended, by using `httpclient.TerraformUserAgent`.
> Adjust UserAgent to use Terraform SDK UserAgent

- dnsimple/data_source_dnsimple_certificate.go
- dnsimple/data_source_dnsimple_certificate_test.go
- dnsimple/provider.go
- website/dnsimple.erb
- website/docs/d/certificate.html.markdown
This allows SSL Certificates created in DNSimple to be applied to other terraform resources. Fixes #3
> Adds a certificate data source

- docs/resources/lets_encrypt_certificate.md
The documentation for the resource was missing and I just added it.
> Adds the documentation for the letsencrypt resource

- dnsimple/config.go
- dnsimple/provider.go
- dnsimple/provider_test.go
The fragment will be appended at the very end of the default user-agent. This enables consumers of the Terraform provider to pass custom tokens to perform additional analytics.
As an example, we will be adding a custom token in the [Consul/DNSimple integration](https://github.com/dnsimple/terraform-dnsimple-cts) to be able to better monitor the usage of the Consul Integration.
> Add ability to pass a custom user agent fragment

- CHANGELOG.md
- dnsimple/config.go
- dnsimple/datasource_dnsimple_certificate.go
- dnsimple/datasource_dnsimple_zone.go
- dnsimple/provider.go
- dnsimple/resource_dnsimple_domain.go
- dnsimple/resource_dnsimple_email_forward.go
- dnsimple/resource_dnsimple_lets_encrypt_certificate.go
- dnsimple/resource_dnsimple_record.go
- dnsimple/resource_dnsimple_zone_record.go
- dnsimple/resource_dnsimple_zone_record_test.go
- dnsimple/zone_record_cache.go
This PR fixes the issues with error propagation made for the provider by using the parent context.
Additionally, it will handle the operation cancellation successfully.
Fixes #57
> Pass the parent context to the calls created by the provider

- CHANGELOG.md
- dnsimple/resource_dnsimple_zone_record.go
- dnsimple/zone_record_cache.go
This will fix the panic when the record cannot be found instead of panicking
References #57
> Avoid panic when looking for a record and it does not exist on the prefetched list

- CHANGELOG.md
- CONTRIBUTING.md
- dnsimple/datasource_dnsimple_certificate_test.go
- dnsimple/resource_dnsimple_lets_encrypt_certificate.go
- dnsimple/resource_dnsimple_lets_encrypt_certificate_test.go
- docs/resources/lets_encrypt_certificate.md
Around June 1 2022 we deprecated the use of the `contact_id` in our API when issuing certificates. The changes were made in dnsimple-go client and this PR ensures they are also reflected in the certificate resource.
> Deprecate contact_id in certificate resource

- CHANGELOG.md
- dnsimple/provider.go
When errors are returned by the DNSimple API we use `attributeErrorsToDiagnostics` to unpack the errors and surface them. However, the implementation only handles `dnsimple.ErrorResponse.AttributeErrors` so when an error is not a `Validation failed` response nothing will be reported and the user will see the following:
```
Error: Provider produced inconsistent result after apply
When applying changes to dnsimple_zone_record.foobar, provider
"provider[\"registry.terraform.io/hashicorp/dnsimple\"]" produced an
unexpected new value: Root resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
How we now report errors:
```
Error: API returned an error: Validation failed
with dnsimple_zone_record.foobar,
on …
```
> Surface all API errors

- dnsimple/resource_dnsimple_zone_record.go
- dnsimple/resource_dnsimple_zone_record_test.go
Fixes #7
Note I have not modified the `dnsimple_record` resource, as it will be removed in the upcoming major version as per #63.
> Fix error while importing record with underscore

- docs/guides/resource-migration.md
- docs/resources/zone_record.md
This PR introduces a migration guide for deprecated resources. The guide is intended to be generic with a detailed example. The example used in the guide is the migration of `dnsimple_record` to `dnsimple_zone_record` which is an actual deprecation change in the provider.
The intended use of the guide going forward is to include a link to it when we are deprecating a resource that has a replacement.
To view the rendered document you can use https://github.com/dnsimple/terraform-provider-dnsimple/pull/67
Supersedes https://github.com/dnsimple/terraform-provider-dnsimple/pull/67
> Document how to migrate a deprecated resource in the form of a guide

- go.mod
- go.sum
This PR:
- Upgrades dependencies to avoid https://github.com/advisories/GHSA-8c26-wmh5-6g9v
- Upgrades dependencies to avoid https://github.com/advisories/GHSA-gwc9-m7rh-j2ww
> Upgrade golang.org/x/crypto to 0.6.0

- CHANGELOG.md
- CONTRIBUTING.md
- dnsimple/resource_dnsimple_lets_encrypt_certificate.go
- dnsimple/resource_dnsimple_lets_encrypt_certificate_test.go
- go.mod
- go.sum
Add the `signature_algorithm` attribute for the `dnsimple_lets_encrypt_certificate` resource.
> Implement signature_algorithm parameter for Let's Encrypt resources

- CHANGELOG.md
- dnsimple/resource_dnsimple_zone_record.go
- dnsimple/resource_dnsimple_zone_record_test.go
It was found that the **prefetch** feature. Which pulls the entire zone and creates a local cache for the provider to use and determine if a record already exists as a performance improvement and a way to reduce the number of API requests. The lookup algorithm did a naive lookup only based on the name of the Resource Record (RR), however, that can yield false positives and also result in incorrect records being created/updated.
Unfortunately, the current version of the TF SDK does not support testing of for_each resources. The algorithm was updated to match all attributes that make a resource unique which are `name`, `type`, and `content`. There is also the potential of using the record ids to match existing records but the current implementation allows for some flexibility when using the …
> Correctly match RRs in the prefetch cache

- CHANGELOG.md
- dnsimple/resource_dnsimple_zone_record.go
As pointed out in #27 our import functionality was creating an empty resource record. The behavior is not compliant with the terraform provider SDK, and also as a user, it would be best if we supply a direct error message when an import fails with the reason for the failure.
This PR refactors the import function to attempt to find the zone record without relying on the `resourceDNSimpleZoneRecordRead` function which has the additional functionality of lookup the prefetch cache. It also directly handles errors and passes them to the user.
**Before**
```
terraform import dnsimple_zone_record.makednshappen_eu_ns1 makednshappen.eu_29676799
dnsimple_zone_record.makednshappen_eu_ns1: Importing from ID "makednshappen.eu_29676799"...
╷
│ Error: The provider returned a resource missing an …
```
> Fix `dnsimple_zone_record` import

- docs/resources/lets_encrypt_certificate.md
- internal/framework/resources/lets_encrypt_certificate_resource.go
- internal/framework/resources/lets_encrypt_certificate_resource_test.go
This allows creating Let's Encrypt certificates with multiple alternate names via Terraform.
Belongs to https://github.com/dnsimple/terraform-provider-dnsimple/issues/92
> Implement support for `alternate_names` on the `dnsimple_lets_encrypt_certificate` resource

- .github/workflows/test.yaml
- GNUmakefile
- docs/resources/domain_delegation.md
- internal/framework/provider/provider.go
- internal/framework/resources/contact_resource.go
- internal/framework/resources/domain_delegation_resource.go
- internal/framework/resources/domain_delegation_resource_test.go
- internal/framework/resources/domain_resource.go
- internal/framework/resources/email_forward_resource.go
- internal/framework/resources/lets_encrypt_certificate_resource.go
- internal/framework/resources/zone_record_resource.go
This creates a resource that will take control of a domain's delegation settings and allow management via Terraform. When the resource is destroyed, only the Terraform state is removed; the domain delegation is kept as is and will no longer be managed by Terraform.
> Implement `dnsimple_domain_delegation` resource

- CHANGELOG.md
- docs/resources/domain_delegation.md
- docs/resources/registered_domain.md
- docs/resources/zone_record.md
- internal/framework/resources/domain_ds_record_resource.go
- internal/framework/resources/registered_domain/common.go
- internal/framework/resources/registered_domain/import.go
- internal/framework/resources/registered_domain/modifiers.go
- internal/framework/resources/registered_domain/modifiers_test.go
- internal/framework/resources/registered_domain/read.go
- internal/framework/resources/registered_domain/resource_test.go
- internal/framework/resources/registered_domain/update.go
This PR adds support for importing registered domains into a `dnsimple_registered_domain` resource.
Also took the opportunity to update documentation across resources and push a fix for a bug I came across in the ds record.
> Import dnsimple_registered_domain with domain name only

- internal/framework/resources/lets_encrypt_certificate_resource.go
- internal/framework/resources/lets_encrypt_certificate_resource_test.go
When the `alternate_names` attribute is omitted in a `dnsimple_lets_encrypt_certificate` resource, an error occurs like "target must be a pointer, got []string, which is a slice". Fixes #109.
> Fix error when no alternate names are provided for the Let's Encrypt certificate resource

- CHANGELOG.md
- docs/resources/registered_domain.md
- go.mod
- go.sum
- internal/framework/resources/registered_domain/common.go
- internal/framework/resources/registered_domain/create.go
- internal/framework/resources/registered_domain/read.go
- internal/framework/resources/registered_domain/resource_test.go
- internal/framework/resources/registered_domain/schema.go
- internal/framework/resources/registered_domain/update.go
Adds the ability to manage the registrar service domain transfer lock as part of the `registered_domain` resource
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1728
Depends on https://github.com/dnsimple/dnsimple-go/pull/147
> Add transfer lock management to registered domain resource

- docs/resources/zone_record.md
- internal/framework/resources/zone_record_resource.go
- internal/framework/resources/zone_record_resource_test.go
This adds the `regions` list attribute to the `zone_record` resource.
> Support regional records

- docs/resources/zone_record.md
- internal/framework/resources/zone_record_resource.go
- internal/framework/resources/zone_record_resource_test.go
As part of increasing our RFC compliance for TXT records we may normalize user-provided content and as a result unless the user provides a normalized version of the record value we will incorrectly write the normalized value to the state resulting in mismatch between the configuration and the written state.
Fixes https://github.com/dnsimple/terraform-provider-dnsimple/issues/165
> Handle normalized record content value

- CHANGELOG.md
- docs/data-sources/zone.md
- docs/resources/zone.md
- internal/framework/datasources/zone_data_source.go
- internal/framework/provider/provider.go
- internal/framework/resources/zone_resource.go
- internal/framework/resources/zone_resource_test.go
We are adding a zone resource in favor of the `dnsimple_zone` data source, so we can add support for the zone active state management. With the new resource, developers can deactivate or activate zones, essentially managing whether a zone is publicly resolving or not. More on the API endpoints used [here](https://developer.dnsimple.com/v2/zones/#activateZoneService).
> Implement Zone resource

- internal/framework/resources/domain_delegation_resource.go
- internal/framework/resources/domain_delegation_resource_test.go
Updates the domain delegation resource name servers attribute to a set.
This should prevent order errors and fix https://github.com/dnsimple/terraform-provider-dnsimple/issues/159
> Update domain delegation name servers to a set

- CHANGELOG.md
- go.mod
- internal/framework/resources/registered_domain/resource_test.go
- internal/framework/resources/registered_domain/update.go
- internal/framework/resources/zone_record_resource.go
- internal/framework/resources/zone_record_resource_test.go
- tools/sweep/main.go
This PR ensure that we correctly handle the cases where the `dnsimple_zone_record` `name` attribute has been normalized by the API.
- Cache search logic updated to use normalized value to avoid false negatives.
- Fixed a bug where the `qualified_name` attribute was set to the record `name` in cases where the name was **empty** (root). It is now set to the zone name.
Closes  #196
> Handle normalized name value for zone_record resource

- .github/workflows/test.yml
- CHANGELOG.md
- internal/framework/datasources/certificate_data_source.go
- internal/framework/datasources/certificate_data_source_test.go
This PR computes the ID for the **dnsimple_certificate** data source using the entire certificate chain. This ensures that if the chain is updated users can act upon the change.
Fixes https://github.com/dnsimple/terraform-provider-dnsimple/issues/208
> Stable certificate data source ID

- internal/framework/resources/domain_delegation_resource.go
We were using the state data during the update operations, and this was resulting in never applying the desired change.
Fixes https://github.com/dnsimple/terraform-provider-dnsimple/issues/256
> Use plan data instead of state in domain delegation updates

- .github/workflows/test.yml
- tools/sweep/main.go
Fixes https://github.com/dnsimple/terraform-provider-dnsimple/issues/271
This PR is simply to update the `registrant_contact_id` in test.yml according to the new DNSimple Sandbox account created to host the domains used in the CI test suite.
- https://github.com/dnsimple/terraform-provider-dnsimple/issues/271#issuecomment-2884416870
> Fixes CI / Acceptance Tests (by updating registrant_contact_id)
